* Who Wrote John?

** Tradition
+ (180 A.D): Iraneus suggests Apostle John wrote the 4th gospel.
  1. (100-150 A.D) no mention of Apostle John
  2. Iraneus used third hand information

** Scholars
+ Believe John did not write gospel
  - Is John an Eye Witness?
    + If he is, why did he not include in his own gospel
      incidents recorded in other gospels where he was
      apparently an eye witness?
      1. Garden of Gethsamane
  - Issue of Language
    + All gospels are in greek
    + Literacy rates were extremely low
    + Disciples in the gospels were said to be uneducated; "without letter" directly translated
    + Highly improbable that an uneducated Jew wrote polished texts in a language he did not grow up speaking


*  Who is the beloved disciple?

** Mentions of beloved disciple
1. Mentioned by Jesus when talking about how it shouldn't matter to Peter how he will die
   versus the beloved disciple. To prove his point he said something along the lines of, "If it is my will
   that the beloved disciple doesn't die until I return, then that is my will" AKA none of your business
   + People misinterpreted Jesus' saying and believed that Jesus would return
     before the beloved disciple returns.
   + (21:22) Gospel of John refutes this rumor "However, Jesus did not say that he would not die, but only, "If I want him to remain until I return, what is that to you?""

** Is John the beloved disciple? Probably No
1. Beloved disciple gains entry to high priest's house, and no Galilean could do that
2. Beloved disciple is at the cross, but other gospels say John was not there

* Editor
Chapters 6 and 21 were most likely added afterwards by an editor, since removing both of them makes the gospel of John flow better in terms of continuity in Jesus' locations and chronology.
