* Community Issues and Concerns in the Gospel of John

* Culpepper 42-48

** Conflict with the Synogogue

*** Lousis Martyn

- Gospel of John can be Read
  1. Ministry of Jesus
  2. Setting within it was written


*** Put out of the Synagogue

  + The word "aposynagogos" (put out of synagogue) was used in gospel of John
  + Farewell Discourse
    - Jesus warns of conflict with Jews
    - Most likely, Johannine Community experienced conflict with Jewish synagogue
  + Giving sight to blind man
    - Jews question parents, but parents are afraid of what Jews would do to them, so they told the Jews to ask go to their son instead
  + Secret Believers
    + John 12:42
    + Some believers kept their faith secret for fear of being put out of the synagogues
      1. Joseph of Arimathea
      2. Nicodemus possibly was a secret believer
  + John 9:22 "Jews had already agreed that anyone who confessed Jesus to be the Messiah would be put out of the synagogue"
    1. Suggests Jews formally banned Christians from synagogues
    2. However, according to other scripture passages, Christians were not denied access
       - Johannine Christians were perhaps specifically excluded from synagogue
       - Or, John was written after Jews and Christians split up
  + Perhaps John was written to strengthen secret believer's faith


** Followers of John the Baptist

John the Baptist
1. John Gospel
   - Unique
     - Not the baptist but witness
     - No narration of Baptism of Jesus
     - John the Baptist elevates Jesus
   - Why?
     - Most likely to counteract a cult of followers who followed John the Baptist who lived in Ephesus, the same location as Johnannine community


** Petrine Christianity

In the Gospel of John, the beloved disciple is always with Peter during major events such as:
1. Finding out who the betrayer was
2. Possibly when Peter denied Jesus
3. At the cross
4. First with Peter to find empty tomb
5. Recognizes risen Lord

Although John shows Peter is an apostle, he tries to remove any reason for worshipping Peter by placing the beloved disciple near his side.


** The Death of the Beloved Disciple

John clears up misunderstanding that Jesus would come back before the beloved disciple died.


* Kysar 26-29

** The purpose of Gospel of John

*** Encourage those in the tension between Jewish and Christian Jewish belief

+ Clarifications
  1. There was no formal law against Christian Jews entering the synagogue
  2. Most Jews were probably fine with Christian Jews
+ Explains why John did some things differently than the synoptics
  1. "the jews" in the Gospel are often the enemy
  2. Portrays Jesus and Moses as heads of opposite sides
  3. Death plot of Jesus starts earlier in gospel
  4. Nicodemus hid his belief in Christianity
+ Purpose
  1. To provide Christian Jews with a way to defend themselves
  2. How Christianity is continuation of Jewish belief and not a break off


*** Encourage and aid Christian Jews who needed to stand up for their faith in the midst of the Roman Empire

+ Help Christians who claimed Jesus was greater than Emperor


*** Whatever purpose was, it was most likely not evangelical nor missionary


* Schneiders 37-46

John was written between 90-135 A.D. making it the last gospel.


*** How is Gospel of John related to the Synoptics?

1. Hypothesis: John, Matthew, and Luke all used "special material" (or material unkown to the others), but John just used more of his special material whereas Matthew and Luke used it only to supplement tradition from Mark
   - John wants audience to understand the Jesus-Story differently than was how it was understood from the other gospels
     + Higher Christology
     + Different relationship between miracles and faith
   - Differences
     + Jesus-Story Sequence
       - Starts with Jesus as Word of God
       - Cleansing of Temple fight is start not end of John unlike synoptics
       - Raising Lazarus is the end


*** Who wrote the Fourth Gospel?

Unlike modern authorship, ancient authorship was less the result of an individual and more the result of a community and its oral and written traditions

Most likely the Beloved Disciple passed down traditions in the Johannine Community, and just before he died the writer of the gospel wrote the gospel.
When the beloved disciple died, the gospel was edited.

** The Johannine Community


